// Types
export { default as bug } from './bug.svg'
export { default as dark } from './dark.svg'
export { default as dragon } from './dragon.svg'
export { default as electric } from './electric.svg'
export { default as fairy } from './fairy.svg'
export { default as fighting } from './fighting.svg'
export { default as fire } from './fire.svg'
export { default as flying } from './flying.svg'
export { default as ghost } from './ghost.svg'
export { default as grass } from './grass.svg'
export { default as ground } from './ground.svg'
export { default as ice } from './ice.svg'
export { default as normal } from './normal.svg'
export { default as poison } from './poison.svg'
export { default as psychic } from './psychic.svg'
export { default as rock } from './rock.svg'
export { default as steel } from './steel.svg'
export { default as water } from './water.svg'

// Other
export { default as menu } from './menu.svg'
export { default as clock } from './clock.svg'
export { default as github } from './github.svg'
export { default as patreon } from './patreon.svg'
export { default as book } from './book.svg'
export { default as down } from './down.svg'
export { default as lokalise } from './lokalise.svg'
