export default {
  project_title: 'Project Grookey',
  your_team: 'Your team',
  select_team: 'Select team',
  team_not_available: 'No teams available',
  friends: 'friends',
  coming_soon: 'Coming soon!',
  links: 'links',
  change_team: 'Change team',
  cookies_description:
    'We use cookies to enhance the user experience and save preferences.',
  clear_data_confirm: "Are you sure you'd like to clear all your data?",
  game_over: 'Game over',
  play_again: 'Play again',
  homepage: 'Home',
  battle_start: 'GO!',
  battle_start_countdown: 'Starting: %1 ...',
  room_code: 'Room code:',
  exit: 'Exit',
  quit: 'Quit',
  waiting_for_player: 'Waiting for a player to join...',
  waiting_for_opponent: 'Waiting for opponent...',
  controls: 'Controls',
  account: 'Account',
  clear_data_confirmation: "Are you sure you'd like to clear all your data?",
  cookies_cleared: 'All cookies cleared.',
  unexpected_error: 'An unexpected error occured',
  invalid_team: 'Your team is invalid.',
  valid_team: 'Your team is valid.',
  invalid_team_object: 'Invalid team object entered.',
  team_copied_succes: 'Team succesfully copied to your clipboard!',
  confirm_team_delete:
    'You cannot undo this action. Are you sure you want to delete this team?',
  teambuilder_signin: 'Please sign in to use the teambuilder.',
  delete: 'Delete',
  export: 'Export',
  no_teams_display: 'No Teams to display',
  add_team: 'Add team',
  add_random_team: 'Get random team',
  import_team: 'Import team',
  meta_not_existing: "Meta %1 doesn't exist",
  not_possible: "Wait, what? That shouldn't happen.",
  exit_invalid_team: 'Are you sure, you want to exit? Your team is invalid.',
  exit_anyway: 'Exit anyway',
  continue_edit: 'Continue editing',
  new_team: 'New team',
  name: 'Name',
  team_name: 'Team name',
  add_new: 'Add new',
  error: "Hold up! There's an error.",
  got_it: 'Got it!',
  quick_play: 'Quick play',
  browse_rooms: 'Browse battle rooms',
  players_online_sing: 'Player online.',
  players_online_plur: 'Players online.',
  used: 'They used   ',
  switching: 'They are switching!',
  charging: 'They are charging up!',
  waiting: 'Waiting...',
  shield_question: 'Shield?',
  shield: 'Shield',
  nice: 'Nice',
  great: 'Great',
  Excellent: 'Excellent',
  charge_tap: 'Tap to charge',
  press: 'Press %1',
  team: 'team',
  settings: 'settings',
  log_out: 'Log out',
  paste_import_team: 'Paste your imported team here.',
  import: 'Import',
  create_room: 'Create room',
  clear_data: 'Clear Data',
  fast_attack_settings: 'Fast Attack / Charge Move Powerup',
  switch_one: 'Switch 1',
  switch_two: 'Switch 2',
  show_keys: 'Show keys',
  charge_one: 'Charge 1',
  charge_two: 'Charge 2',
  cp: 'cp',
  corrupted_data_warning: 'This Pokemon has corrupted data!',
  shiny_question: 'Shiny?',
  gender_question: 'Gender',
  gender_male: 'Male',
  gender_female: 'Female',
  gender_neutral: 'Neutral',
  nickname: 'Nickname',
  clear: 'Clear',
  fast_move: 'Fast move',
  charge_moves: 'Charge moves',
  level: 'Level',
  ivs: 'IVs',
  attack_abbr: 'ATK',
  defense_abbr: 'DEF',
  hitpoints_abbr: 'HP',
  suggestions_none: 'There are no suggestions',
  connect_db_failed: 'Failed to connect to the Pokemon database.',
  pokemon_plant: '(Plant)',
  pokemon_trash: '(Thrash)',
  pokemon_sandy: '(Sandy)',
  pokemon_sunny: '(Sunny)',
  pokemon_shadow: '(Shadow)',
  pokemon_east: '(East)',
  pokemon_west: '(West)',
  pokemon_overcast: '(Overcast)',
  pokemon_origin: '(Origin)',
  pokemon_altered: '(Altered)',
  pokemon_land: '(Land)',
  pokemon_galarian: '(Galarian)',
  pokemon_zen: '(Zen)',
  pokemon_standard: '(Standard)',
  pokemon_therian: '(Therian)',
  pokemon_incarnate: '(Incarnate)',
  pokemon_white: '(White)',
  pokemon_black: '(Black)',
  pokemon_ordinary: '(Ordinary)',
  pokemon_resolute: '(Resolute)',
  pokemon_aria: '(Aria)',
  pokemon_pirouette: '(Pirouette)',
  pokemon_burn: '(Burn)',
  pokemon_chill: '(Chill)',
  pokemon_douse: '(Douse)',
  pokemon_shock: '(Shock)',
  pokemon_mega: '(Mega)',
  pokemon_alolan: '(Alolan)',
  flying: 'Flying',
  pokemon_libre: '(Libre)',
  pokemon_armored: '(Armored)',
  pokemon_rainy: '(Rainy)',
  pokemon_snowy: '(Snowy)',
  pokemon_attack: '(Attack)',
  pokemon_speed: '(Speed)',
  pokemon_defense: '(Defense)',
  pokemon_fan: '(Fan)',
  pokemon_frost: '(Frost)',
  pokemon_heat: '(Heat)',
  pokemon_mow: '(Mow)',
  pokemon_wash: '(Wash)',
  pokemon_kariyushi: '(Kariyushi)',
  pokemon_rockstar: '(Rock Star)',
  pokemon_popstar: '(Pop Star)',
  pokemon_5thanniversary: '(5th Anniversary)',
  bug: 'Bug',
  dark: 'Dark',
  normal: 'Normal',
  dragon: 'Dragon',
  electric: 'Electric',
  fairy: 'Fairy',
  fighting: 'Fighting',
  fire: 'Fire',
  ghost: 'Ghost',
  grass: 'Grass',
  ground: 'Ground',
  ice: 'Ice',
  poison: 'Poison',
  psychic: 'Psychic',
  rock: 'Rock',
  steel: 'Steel',
  water: 'Water',
  pokemon_female: '(Female)',
  excellent: 'Excellent',
  choose_pokemon: 'Choose pokemon',
  start: 'Start',
  hold_fastkey_button: 'Hold %1',
  knock_out: "It's a KO!",
  result_win: 'You won the game',
  result_loss: 'You lost the game',
  result_tie: 'The game ended in a tie',
  team_verify_wrong_length: 'Wrong number of Pokemon %1. Should be 6.',
  team_verify_invalid_id: "Pokemon with id %1 doesn't exist.",
  team_verify_invalid_attack:
    'Pokemon in index %1 has an invalid attack iv of %2.',
  team_verify_invalid_defense:
    'Pokemon in index %1 has an invalid defense iv of %2.',
  team_verify_invalid_hp: 'Pokemon in index %1 has an invalid hp iv of %2.',
  team_verify_invalid_level: 'Pokemon in index %1 has an invalid level of %2.',
  team_verify_invalid_cp: 'Pokemon in index %1 has too many cp: %2.',
  team_verify_invalid_nickname:
    'The nickname %1 exceeds the character limit of 12.',
  team_verify_cursed_nickname:
    "We don't like the nickname %1. Your pokémon have feelings, too.",
  team_verify_clause_by_dex:
    'Pokemon in index %1 is a duplicate and violates the species clause by dex.',
  team_verify_clause_by_form:
    'Pokemon in index %1 is a duplicate and violates the species clause by form.',
  team_verify_clause_by_type:
    'Pokemon in index %1 is a duplicate and violates the type clause.',
  team_verify_invalid_bestbuddy:
    'Team has %1 best buddies, which is more as the allowed %2.',
  team_verify_invalid_megas:
    'Team has %1 mega Pokemon, which is more as the allowed %2.',
  team_verify_invalid_points:
    'Team uses %1 points, which is more as the allowed %2.',
  team_verify_invalid_class: "Team doesn't match any class.",
  team_verify_invalid_move: "Pokemon in index %1 can't use %2.",
  team_verify_banned_pokemon: 'Pokemon in index %1 is banned',
  team_verify_invalid_pokemon: "Pokemon in index %1 isn't allowed.",
  pokemon_sky: '(Sky)',
  preferences: 'Preferences',
  translations: 'Translations',
  teamSearch: 'Search Team / Meta',
  offer_account: 'Login or Create an Account',
  offer_guest: 'Play as guest',
  error_please_authenticate:
    'If you want to play, you need to login with an account. You can also play as a guest, but guest players can only play unranked.',
  not_authenticated_title: 'You are not authenticated',
  start_teampreview_timer: 'Start timer',
  login_homepage: 'Login or Create an Account!',
  join_battle: 'Join the battle!',
  login_button_google: 'Login with Google',
  login_more_options: 'More sign in options coming soon!',
  user_logged_in_name: 'Logged in as %1',
  logged_in: 'Logged in.',
  logged_in_as: 'Logged In As:',
  start_battling: 'Start battling',
  no_username:
    "Your account doesn't have a username.Please choose a unique name for your account.You may change it later in the settings.",
  duplicate_username:
    'This username already exists. Please choose another one.',
  username_change_settings: 'Change username',
  username_change_confirm: 'Confirm',
  username_unchanged: "That's your old name",
  username_change_success: 'Username successfully changed',
  fr_popup_header_default: 'Do you want to send a friend request to %1?',
  fr_popup_header_error: "Friend request to %1 doesn't work.",
  fr_popup_header_success: 'Friend request was sent successfully to %1.',
  yes: 'Yes',
  no: 'No',
  close: 'Close',
  send_fr_to_self_error: 'This is you',
  user_does_not_exist_error: "A user with this name doesn't exist",
  fr_duplicate_error: "You've already sent a friend request to %1",
  fr_conflict_error: "You've already received a friend request from %1",
  send_friend_request: 'Send friend request',
  send: 'Send',
  challenge: 'Challenge',
  unfriend: 'Unfriend',
  cancel: 'Cancel',
  no_team_with_format_error: "You don't have a team for the format %1",
  accept: 'Accept',
  decline: 'Decline',
  confirm: 'Confirm',
  unfriend_confirm: 'Friendship ended with %1',
  unfriend_popup_title: 'Unfriend %1?',
  challenge_declined_title: 'Challenge declined',
  challenge_declined_message: '%1 declined your challenge.',
  used_chargemove_message: '%1 used %2!',
  it_was_shielded_message: 'It was shielded!',
  stat_change_message: "%1's stats were changed.",
  challenges_header: 'Challenges (%1)',
  friend_requests: 'Friend Requests',
  recently_played: 'Recently played',
  new_friend_input_desc: "Type in the new friend's username",
  go_to_friends_console: 'More details',
  autorekt_tooltip:
    'In this gamemode you and your opponent both get random pokemon and moves.',
  challenges_tooltip: 'When a friend challenges you, it will appear here.',
  timer_tooltip:
    'Starts a timer of 90 seconds. If time runs out, the matchup ends.',
  cleardata_tooltip: 'Clears all locally stored data and cookies.',
  language: 'Language',
}
